// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:flutter/painting.dart';

const blueCowTheme = {
  'root':
      TextStyle(backgroundColor: Color(0xff282936), color: Color(0xffe9e9f4)),
  'tag': TextStyle(color: Color(0xff62d6e8)),
  'subst': TextStyle(color: Color(0xffe9e9f4)),
  'strong': TextStyle(color: Color(0xff00f769), fontWeight: FontWeight.bold),
  'emphasis': TextStyle(color: Color(0xffb45bcf), fontStyle: FontStyle.italic),
  'bullet': TextStyle(color: Color(0xffea51b2)),
  'quote': TextStyle(color: Color(0xffa1efe4)),
  'number': TextStyle(color: Color(0xffb45bcf)),
  'regexp': TextStyle(color: Color(0xffa1efe4)),
  'literal': TextStyle(color: Color(0xffb45bcf)),
  'link': TextStyle(color: Color(0xffb45bcf)),
  'code': TextStyle(color: Color(0xffebff87)),
  'title': TextStyle(color: Color(0xff00f769)),
  'section': TextStyle(color: Color(0xff62d6e8)),
  'selector-class': TextStyle(color: Color(0xffb45bcf)),
  'keyword': TextStyle(color: Color(0xffb45bcf)),
  'selector-tag': TextStyle(color: Color(0xffea51b2)),
  'name': TextStyle(color: Color(0xffea51b2)),
  'attr': TextStyle(color: Color(0xffb45bcf)),
  'symbol': TextStyle(color: Color(0xffb45bcf)),
  'attribute': TextStyle(color: Color(0xff62d6e8)),
  // 'params': TextStyle(color: Color(0xfff8f8f2)),
  'string': TextStyle(color: Color(0xffebff87)),
  'type': TextStyle(color: Color(0xffb45bcf)),
  'built_in': TextStyle(color: Color(0xffa1efe4)),
  //'builtin-name': TextStyle(color: Color(0xffe6db74)),
  // 'selector-id': TextStyle(color: Color(0xffe6db74)),
  // 'selector-attr': TextStyle(color: Color(0xffe6db74)),
  // 'selector-pseudo': TextStyle(color: Color(0xffe6db74)),
  'addition': TextStyle(color: Color(0xffebff87)),
  'variable': TextStyle(color: Color(0xffea51b2)),
  'template-variable': TextStyle(color: Color(0xffea51b2)),
  'comment': TextStyle(color: Color(0xff626483)),
  'deletion': TextStyle(color: Color(0xffea51b2)),
  'meta': TextStyle(color: Color(0xff00f769)),
};
