name: flutter_highlight
description: Syntax highlighting widget for Flutter with lots of languages and themes support.
version: 0.7.2
publish_to: none
homepage: https://github.com/git-touch/highlight

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  highlight:
    git:
      url: git@github.com:nank1ro/highlight.dart
      ref: v0.7.1
      path: packages/highlight

dev_dependencies:
  flutter_test:
    sdk: flutter
# dependency_overrides:
#   highlight:
#     path: ../highlight
