name: highlight
description: Syntax highlighting for Dart with lots of languages and themes support.
version: 0.7.1
publish_to: none
homepage: https://github.com/pd4d10/highlight

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  path: ^1.8.0
  pedantic: ^1.11.0
  test: ^1.17.5
