# This is a basic workflow to help you get started with Actions

name: Create Github release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Dart SDK
        # You may pin to the exact commit or the version.
        # uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        uses: dart-lang/setup-dart@v1.0
        # with:
          # The channel, or a specific version from a channel to install ('stable', 'beta', 'dev', '2.7.2', '2.12.0-1.4.beta'). Using one of the three channels instead of a version will give you the latest version published to that channel.
          # sdk: # optional, default is stable
          # The CPU architecture ('x64', 'ia32', 'arm', or 'arm64').
          # architecture: # optional, default is x64
      
      - name: Get version
        id: version
        run: |
            pub global activate pubspec_version
            cd packages/highlight
            echo "::set-output name=PUBSPEC_VERSION::$(pubver get)"
  
      - name: Automatic Releases
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
            # GitHub secret token
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: "v${{ steps.version.outputs.PUBSPEC_VERSION }}"
            prerelease: false
